package com.example.sustainance.constants;

import com.example.sustainance.models.ingredients.Ingredient;
import java.util.Arrays;
import java.util.List;

public class baseIngredients {
    public static final List<Ingredient> BASE_INGREDIENTS = List.of(
            // Grains & Carbs (weight-based)
            new Ingredient("All-purpose flour", 0, "grams", "Grains & Carbs",
                    Arrays.asList("grams", "kg", "cups")),
            new Ingredient("Rice", 0, "grams", "Grains & Carbs",
                    Arrays.asList("grams", "kg", "cups")),
            new Ingredient("Pasta (e.g. spaghetti)", 0, "grams", "Grains & Carbs",
                    Arrays.asList("grams", "kg")),
            new Ingredient("Bread", 0, "slices", "Grains & Carbs",
                    Arrays.asList("slices", "piece")),
            new Ingredient("Oats (rolled)", 0, "grams", "Grains & Carbs",
                    Arrays.asList("grams", "kg", "cups")),

            // Vegetables (count or weight)
            new Ingredient("Onion", 0, "piece", "Vegetables",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Garlic", 0, "clove", "Vegetables",
                    Arrays.asList("clove", "piece", "grams")),
            new Ingredient("Tomato", 0, "piece", "Vegetables",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Carrot", 0, "piece", "Vegetables",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Bell pepper", 0, "piece", "Vegetables",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Potato", 0, "piece", "Vegetables",
                    Arrays.asList("piece", "count", "grams", "kg")),
            new Ingredient("Spinach", 0, "grams", "Vegetables",
                    Arrays.asList("grams", "kg", "cups")),
            new Ingredient("Broccoli", 0, "grams", "Vegetables",
                    Arrays.asList("grams", "kg", "piece")),

            // Meat & Fish (weight-based)
            new Ingredient("Chicken breast", 0, "grams", "Meat & Fish",
                    Arrays.asList("grams", "kg", "piece")),
            new Ingredient("Ground beef", 0, "grams", "Meat & Fish",
                    Arrays.asList("grams", "kg")),
            new Ingredient("Fish fillet (e.g. salmon)", 0, "grams", "Meat & Fish",
                    Arrays.asList("grams", "kg", "piece")),
            new Ingredient("Eggs", 0, "piece", "Meat & Fish",
                    Arrays.asList("piece", "count")),
            new Ingredient("Bacon", 0, "grams", "Meat & Fish",
                    Arrays.asList("grams", "slices")),

            // Dairy (volume or weight)
            new Ingredient("Milk", 0, "ml", "Dairy",
                    Arrays.asList("ml", "l", "cups")),
            new Ingredient("Cheese (cheddar)", 0, "grams", "Dairy",
                    Arrays.asList("grams", "kg", "slices")),
            new Ingredient("Yogurt (plain)", 0, "grams", "Dairy",
                    Arrays.asList("grams", "kg", "cups")),
            new Ingredient("Butter", 0, "grams", "Dairy",
                    Arrays.asList("grams", "kg", "tbsp")),
            new Ingredient("Cream", 0, "ml", "Dairy",
                    Arrays.asList("ml", "l", "cups")),

            // Spices & Herbs (small measurements)
            new Ingredient("Salt", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams")),
            new Ingredient("Black pepper", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams")),
            new Ingredient("Cinnamon", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams")),
            new Ingredient("Cumin", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams")),
            new Ingredient("Oregano", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams")),
            new Ingredient("Basil", 0, "tsp", "Spices & Herbs",
                    Arrays.asList("tsp", "tbsp", "grams", "leaves")),

            // Liquids & Oils (volume-based)
            new Ingredient("Olive oil", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml", "l", "cups")),
            new Ingredient("Vegetable oil", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml", "l", "cups")),
            new Ingredient("Soy sauce", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml")),
            new Ingredient("Vinegar (white)", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml")),
            new Ingredient("Lemon juice", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml")),
            new Ingredient("Honey", 0, "tbsp", "Others",
                    Arrays.asList("tbsp", "tsp", "ml", "grams")),

            // Fruits (count or weight)
            new Ingredient("Apple", 0, "piece", "Fruits",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Banana", 0, "piece", "Fruits",
                    Arrays.asList("piece", "count", "grams")),
            new Ingredient("Lemon", 0, "piece", "Fruits",
                    Arrays.asList("piece", "count")),
            new Ingredient("Strawberry", 0, "grams", "Fruits",
                    Arrays.asList("grams", "kg", "cups", "piece")),

            // Flours & Bases
            new Ingredient("Whole wheat flour", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Bread flour", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Cake flour", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Self-raising flour", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),

            // Sugars & Sweeteners
            new Ingredient("White sugar", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups", "tablespoons")),
            new Ingredient("Brown sugar", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups", "tablespoons")),
            new Ingredient("Powdered sugar", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Maple syrup", 0, "ml", "Baking & Sweets",
                    Arrays.asList("ml", "tablespoons", "cups")),
            new Ingredient("Vanilla extract", 0, "ml", "Baking & Sweets",
                    Arrays.asList("ml", "teaspoons")),

            // Chocolate & Cocoa
            new Ingredient("Dark chocolate", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "ounces", "squares")),
            new Ingredient("Milk chocolate", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "ounces", "squares")),
            new Ingredient("White chocolate", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "ounces", "squares")),
            new Ingredient("Cocoa powder", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "tablespoons", "cups")),
            new Ingredient("Chocolate chips", 0, "grams", "Baking & Sweets",
                    Arrays.asList("grams", "cups")),

            // Dried Legumes
            new Ingredient("Black beans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Kidney beans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Chickpeas", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Lentils (red)", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Lentils (green)", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Lentils (brown)", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Split peas", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups")),
            new Ingredient("Black-eyed peas", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Navy beans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Pinto beans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),
            new Ingredient("Lima beans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "cans")),

            // Tree Nuts
            new Ingredient("Almonds", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "pieces")),
            new Ingredient("Walnuts", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "halves")),
            new Ingredient("Cashews", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "pieces")),
            new Ingredient("Pecans", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "halves")),
            new Ingredient("Hazelnuts", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "pieces")),
            new Ingredient("Brazil nuts", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "pieces")),
            new Ingredient("Macadamia nuts", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "cups", "pieces")),
            new Ingredient("Pine nuts", 0, "grams", "Legumes & Nuts",
                    Arrays.asList("grams", "tablespoons", "cups"))
    );
}