package com.example.sustainance.constants;

import com.example.sustainance.models.ingredients.Ingredient;

import java.util.List;

public class baseIngredients {
    public static final List<Ingredient> BASE_INGREDIENTS = List.of(
            new Ingredient("All-purpose flour", "grams", 0),
            new Ingredient("Sugar (granulated)", "grams", 0),
            new Ingredient("Salt", "grams", 0),
            new Ingredient("Baking powder", "grams", 0),
            new Ingredient("Baking soda", "grams", 0),
            new Ingredient("Yeast (dry)", "grams", 0),
            new Ingredient("Cornstarch", "grams", 0),
            new Ingredient("Brown sugar", "grams", 0),
            new Ingredient("Cinnamon", "grams", 0),
            new Ingredient("Cumin", "grams", 0),
            new Ingredient("Paprika", "grams", 0),
            new Ingredient("Chili powder", "grams", 0),
            new Ingredient("Oregano", "grams", 0),
            new Ingredient("Basil", "grams", 0),
            new Ingredient("Breadcrumbs", "grams", 0),
            new Ingredient("Chocolate chips", "grams", 0),
            new Ingredient("Nuts (mixed)", "grams", 0),
            new Ingredient("Raisins", "grams", 0),
            new Ingredient("Oats (rolled)", "grams", 0),

            new Ingredient("Olive oil", "milliliters", 0),
            new Ingredient("Milk", "milliliters", 0),
            new Ingredient("Soy sauce", "milliliters", 0),
            new Ingredient("Vinegar (white)", "milliliters", 0),
            new Ingredient("Lemon juice", "milliliters", 0),
            new Ingredient("Mayonnaise", "milliliters", 0),
            new Ingredient("Ketchup", "milliliters", 0),
            new Ingredient("Mustard", "milliliters", 0),
            new Ingredient("Honey", "milliliters", 0),
            new Ingredient("Coconut milk", "milliliters", 0),
            new Ingredient("Vanilla extract", "milliliters", 0),
            new Ingredient("Maple syrup", "milliliters", 0),
            new Ingredient("Cream", "milliliters", 0),

            new Ingredient("Eggs", "count", 0),
            new Ingredient("Garlic", "count", 0),
            new Ingredient("Onion", "count", 0),
            new Ingredient("Tomato", "count", 0),
            new Ingredient("Carrot", "count", 0),
            new Ingredient("Bell pepper", "count", 0),
            new Ingredient("Lettuce", "count", 0),
            new Ingredient("Cucumber", "count", 0),
            new Ingredient("Zucchini", "count", 0),
            new Ingredient("Potato", "count", 0),
            new Ingredient("Sweet potato", "count", 0),
            new Ingredient("Apple", "count", 0),
            new Ingredient("Banana", "count", 0),
            new Ingredient("Orange", "count", 0),

            new Ingredient("Spinach", "grams", 0),
            new Ingredient("Broccoli", "grams", 0),
            new Ingredient("Cauliflower", "grams", 0),
            new Ingredient("Mushroom", "grams", 0),
            new Ingredient("Green beans", "grams", 0),
            new Ingredient("Corn (kernels)", "grams", 0),
            new Ingredient("Strawberry", "grams", 0),
            new Ingredient("Blueberry", "grams", 0),

            new Ingredient("Chicken breast", "grams", 0),
            new Ingredient("Ground beef", "grams", 0),
            new Ingredient("Beef steak", "grams", 0),
            new Ingredient("Pork chops", "grams", 0),
            new Ingredient("Bacon", "grams", 0),
            new Ingredient("Fish fillet (e.g. salmon)", "grams", 0),
            new Ingredient("Shrimp", "grams", 0),
            new Ingredient("Tofu", "grams", 0),
            new Ingredient("Chickpeas", "grams", 0),
            new Ingredient("Lentils", "grams", 0),
            new Ingredient("Kidney beans", "grams", 0),
            new Ingredient("Black beans", "grams", 0),
            new Ingredient("Cheese (cheddar)", "grams", 0),
            new Ingredient("Yogurt (plain)", "grams", 0),
            new Ingredient("Peanut butter", "grams", 0),

            new Ingredient("Rice", "grams", 0),
            new Ingredient("Pasta (e.g. spaghetti)", "grams", 0)
    );
}
