spring:
  application:
    name: SustAInance
server:
  port: 9097
google:
  key: ${GOOGLE_KEY}
ai:
  github:
    key: ${GITHUB_TOKEN}
    url: https://models.inference.ai.azure.com
    model: gpt-4o
  cache:
    enabled: true
    ttl-hours: 1
    max-size: 500
  openai:
    max-tokens: 1500
    temperature: 0.7
    timeout: 30000
  prompts:
    recipe:
      system-message: "You are a professional chef with 20 years of experience creating delicious, practical recipes."
    meal-plan:
      system-message: "You are a professional nutritionist and chef specializing in meal planning."