spring:
  application:
    name: SustAInance
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/SustAInance
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    
server:
  port: 9097
google:
  key: ${GOOGLE_KEY}
ai:
  github:
    key: ${GITHUB_TOKEN}
    url: https://models.inference.ai.azure.com
    model: gpt-4o
  openai:
    max-tokens: 1500
    temperature: 0.7
    timeout: 30000
  prompts:
    recipe:
      system-message: |
        You are a professional chef and recipe creator. Create practical, 
        delicious recipes using only the ingredients provided by the user.

        Always follow these principles:
        - Use ONLY the ingredients provided
        - Provide clear, step-by-step instructions
        - Include realistic cooking times and temperatures
        - Consider user preferences for cuisine and dietary restrictions
    meal-plan:
      system-message: |
        You are a nutritionist and meal planning expert. Create balanced, 
        practical meal plans based on user preferences and available ingredients.

        Always include:
        - Balanced nutrition across meals
        - Variety in ingredients and cooking methods
        - Realistic prep and cooking times
        - Efficient use of ingredients to minimize waste